### ISSUE TITLE
Issues compiling with spack

### ISSUE THREAD

**Issue by samueljackson92** [stefaniereuter/wands#23]
Hi, 

I'm trying to compile the Wands server inside a spack environment following the instructions in the README.

Firstly I noticed that I needed to additionally add cmake to the spack as I am using a fresh VM which did not already contain them.

When I got to running cmake I get the following message:

```bash
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HDF5 CXX compiler wrapper is unable to compile a minimal HDF5 program.
CMake Warning at /home/ubuntu/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-12.3.0/cmake-3.26.3-63ei2xym4v4coc6nhvfow4zlmuhpdhuq/share/cmake-3.26/Modules/FindHDF5.cmake:737 (message):
  HDF5 found for language CXX is not parallel but previously found language
  is parallel.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /home/ubuntu/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-12.3.0/cmake-3.26.3-63ei2xym4v4coc6nhvfow4zlmuhpdhuq/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HDF5 (missing: HDF5_INCLUDE_DIRS) (found version "")
Call Stack (most recent call first):
  /home/ubuntu/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-12.3.0/cmake-3.26.3-63ei2xym4v4coc6nhvfow4zlmuhpdhuq/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/ubuntu/spack/opt/spack/linux-ubuntu22.04-cascadelake/gcc-12.3.0/cmake-3.26.3-63ei2xym4v4coc6nhvfow4zlmuhpdhuq/share/cmake-3.26/Modules/FindHDF5.cmake:1001 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)

```   

Which looks like it cannot find HDF5. Checking the environment variables I can see that the `CMAKE_PREFIX_PATH` appears to be set to the correct place:

```bash
CMAKE_PREFIX_PATH=/home/ubuntu/spack/var/spack/environments/wands/.spack-env/view
``` 

And checking `$CMAKE_PREFIX_PATH/include` shows me that there are HDF5 headers there. 

Any ideas why this is not working?

My spack environment file looks like the following:

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - adios2@2.9+dataman+python
  - boost
  - cmake
  - openmpi
  - hdf5
  view: true
  concretizer:
    unify: true
  compilers:
  - compiler:
      spec: gcc@=12.3.0
      paths:
        cc: /usr/bin/gcc-12
        cxx: /usr/bin/g++-12
        f77: /usr/bin/gfortran-12
        fc: /usr/bin/gfortran-12
      flags: {}
      operating_system: ubuntu22.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu22.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
  - compiler:
      spec: gcc@=9.5.0
      paths:
        cc: /usr/bin/gcc-9
        cxx: /usr/bin/g++-9
        f77: null
        fc: null
      flags: {}
      operating_system: ubuntu22.04
      target: x86_64
      modules: []

```
